// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOhlnkGP_Ryeib6YGD-4LDJwL6OArRZLo',
    appId: '1:655710366874:web:7bdc844469a2a3fc6e8323',
    messagingSenderId: '655710366874',
    projectId: 'earthuswap-dev',
    authDomain: 'earthuswap-dev.firebaseapp.com',
    databaseURL:
        'https://earthuswap-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'earthuswap-dev.appspot.com',
    measurementId: 'G-3E46R6ZWL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOhlnkGP_Ryeib6YGD-4LDJwL6OArRZLo',
    appId: '1:655710366874:android:3b0d4205afba17076e8323',
    messagingSenderId: '655710366874',
    projectId: 'earthuswap-dev',
    databaseURL:
        'https://earthuswap-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'earthuswap-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUCrkX70scqtthY9AJB8oZ_vQ7km8MO0E',
    appId: '1:655710366874:ios:598afc002e32f5396e8323',
    messagingSenderId: '655710366874',
    projectId: 'earthuswap-dev',
    databaseURL:
        'https://earthuswap-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'earthuswap-dev.appspot.com',
    iosClientId:
        '655710366874-lfpg95pj9db3ublha6dln380jtv9mltb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUCrkX70scqtthY9AJB8oZ_vQ7km8MO0E',
    appId: '1:655710366874:ios:8eaca542b38923a06e8323',
    messagingSenderId: '655710366874',
    projectId: 'earthuswap-dev',
    databaseURL:
        'https://earthuswap-dev-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'earthuswap-dev.appspot.com',
    iosClientId:
        '655710366874-kbu4ds8tg39s0sh9hknbcoroj35gn7h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin.RunnerTests',
  );
}
